### ISSUE TITLE
Add comments to the Post

### ISSUE THREAD

**Issue by lipis** [welovecoding/vote4code#10]
I'm guessing simple comments in the beginning.. no threads or anything :)

**Comment by bennyn** [comment]
Yeah, threads suck. Cast a vote if you think otherwise^^

**Comment by blender** [comment]
Line quoting in comments? a-la-github  https://github.com/welovecoding/vote4code/blob/master/main/app.yaml#L10

**Comment by lipis** [comment]
noooooooooooooooooooooo!! :/

**Comment by blender** [comment]
Can close?

**Comment by bennyn** [comment]
Can close. 👍
