### ISSUE TITLE
Line Numbers

### ISSUE THREAD

**Issue by blender** [welovecoding/vote4code#17]
As a user I want to see line number to the left of the code battles in each of the alternatives

**Comment by bennyn** [comment]
With a plugin this should be doable: https://github.com/wcoder/highlightjs-line-numbers.js/

**Comment by lipis** [comment]
Let's see if these instructions make sense :)
http://docs.gae-init.appspot.com/howto/#add_frontend

**Comment by bennyn** [comment]
I like your way of teaching. 😄
