### ISSUE TITLE
Add "Fork me on GitHub" ribbon

### ISSUE THREAD

**Issue by bennyn** [welovecoding/vote4code#22]
Instead of a GitHub button we should have a GitHub ribbon.

**Screenshot**

![Screenshot](https://cloud.githubusercontent.com/assets/469989/25727342/f121d188-3128-11e7-9bbe-21982f4c4303.png)

**Comment by lipis** [comment]
Nooo... this project is not there to be forked.. :) It's just an open source platform.. not a library :)

**Comment by bennyn** [comment]
ok
