### ISSUE TITLE
Make descriptive URLs instead of IDs

### ISSUE THREAD

**Issue by kbariotis** [welovecoding/vote4code#25]
This e.g:

`https://vote4code.com/post/5086441721823232/` 

could better be written like this:

`https://vote4code.com/post/react-components-style/`
`https://vote4code.com/post/react-components-functional-vs-classes/`

etc, ...

This would improve SEO and allow for performant sharing on social media.

Great work! :)

**Comment by bennyn** [comment]
Solved by https://github.com/welovecoding/vote4code/pull/30 👏
