### ISSUE TITLE
Meaningful description of what "vote4code" is

### ISSUE THREAD

**Issue by bennyn** [welovecoding/vote4code#35]
On our frontpage we need to tell what "vote4code" is about. I will leave this issue to create ideas and texts in order to describe our "mission" in a snappy and meaningful way...

**Comment by bennyn** [comment]
**Do you have two solutions for a coding problem?** If yes, then [vote4code](https://vote4code.com/) is just right for you.

With [vote4code](https://vote4code.com/) you can cast a vote on which solution is the best. Simply upload both code snippets and let our community vote for you. It's easy as that.

**Comment by lipis** [comment]
We can have random questions on top showing a different one every time..

- Are you arguing over "important"  things like different coding style at work?
- Is your [OCD](https://en.m.wikipedia.org/wiki/Obsessive–compulsive_disorder) getting worse every time you code review your colleges?
- Are you fight with your inner self over different solutions for the same problem?

**Comment by bennyn** [comment]
**New tagline**

## vote4code
### Debating on code has never been easier!

        1. Submit two code snippets
        2. Select a title for your code battle
        3. Let our community vote!

**Screenshot**

![unbenannt](https://cloud.githubusercontent.com/assets/469989/25771051/bf712d54-3246-11e7-9498-a55f4e03c564.PNG)
