### ISSUE TITLE
Make the "Code Fight" more obvious

### ISSUE THREAD

**Issue by bennyn** [welovecoding/vote4code#6]
When viewing a vote it should be clear that "Variant A" and "Variant B" are counterparties. Design-wise it should look like "Variant A vs. Variant B", so the page should look like a boxing ring or wrestling arena. 😀

**Comment by blender** [comment]
http://www.fightersgeneration.com/np5/gm/sf2-s4.gif

**Comment by bennyn** [comment]
Solved by https://github.com/welovecoding/vote4code/pull/30 👏
