### ISSUE TITLE
"Other" programming language

### ISSUE THREAD

**Issue by oldmud0** [welovecoding/vote4code#75]
There are too many languages out there, so why not just have people type in their own?

**Comment by bennyn** [comment]
Good suggestion! We will create a form where people can submit languages (but we have to moderate that in case of spamming / abuse). For now we will create a "Other" field, so that you can already post snippets for other languages. :)

**Comment by bennyn** [comment]
@lipis, maybe we should add a small link next to "Language" which states something like: "Missing a programming language here? Submit one".

**Comment by bennyn** [comment]
@oldmud0 We now have the option to select "Other". 😃 

@lipis I created a PR to make it easier to submit new programming languages: https://github.com/welovecoding/vote4code/pull/84

**Comment by lipis** [comment]
Done :)
