### ISSUE TITLE
Add Blue and Red to "Variant A" and "Variant B"

### ISSUE THREAD

**Issue by bennyn** [welovecoding/vote4code#76]
On our page we call the code snippets "Blue Corner" and "Red Corner". But when submitting it's written "Variant A" and "Variant B". If we would simply rename it to "Blue Corner" and "Red Corner" people might get confused what to enter there. So my suggestion is:

"Variant A" -> "Variant A (Red Corner)"
"Variant B" -> "Variant B (Blue Corner)"

**Comment by lipis** [comment]
Done in #74 - Will style it in another PR :)
