### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by brianbowden** [welovecoding/vote4code#92]
You need Kotlin as a language choice! It's the Java replacement!

**Comment by bennyn** [comment]
Hey @brianbowden, your wish is our command! 

Looking forward to see the first Kotlin fight now. 😉

**Screenshot**

![unbenannt](https://user-images.githubusercontent.com/469989/27283535-0c26cda4-54f5-11e7-88f3-fcd00a881fb6.png)
